config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "family_members#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :family_members do
    resources :orders, only: %i[new create]
  end
  resources :orders, only: %i[show index] do
    resources :reviews, only: %i[new create]
  end
  resources :orders, only: %i[show index destroy]
  resources :users, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/family_member.rb
class FamilyMember < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :reviews, through: :orders
  has_one_attached :photo
  belongs_to :user

  validates :first_name, :last_name, :kinship, :description, :profile_title, :value_hour, :photo, presence: true
  validates :value_hour, numericality: { greater_than: 0 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :family_member
  has_one :review, dependent: :destroy

  validates :quantity_hour, :rent_date, presence: true
  validates :quantity_hour, numericality: { greater_than: 0 }
  validate :rent_date_cannot_be_in_the_past

  private

  def rent_date_cannot_be_in_the_past
    if rent_date.present? && rent_date < Date.today
      errors.add(:rent_date, "can't be in the past")
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :order

  validates :content, :rating, presence: true
  validates :content, length: { maximum: 600 }
  validates :content, length: { minimum: 70 }
  validates :rating, numericality: { greater_than: 0, less_than_or_equal_to: 5 }
  validates :order_id, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :family_members, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name photo])
  end
end

app/controllers/family_members_controller.rb
class FamilyMembersController < ApplicationController
  before_action :set_family_member, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @family_members = FamilyMember.all
    @orders = Order.all
  end

  def show
    @name = "#{@family_member[:first_name]} #{@family_member[:last_name]}"
    @reviews = Review.joins(:order).where(order: { family_member_id: @family_member.id })
    @user = current_user
  end

  def new
    @family_member = FamilyMember.new
  end

  def create
    @family_member = FamilyMember.new(family_member_params)
    @family_member.user = current_user
    if @family_member.save
      redirect_to family_member_path(@family_member)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @family_member.update(family_member_params)
      redirect_to family_member_path(@family_member)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = current_user
    if @family_member.orders.any?
      flash[:alert] = "Você não pode deletar alguém que contenha pedidos em aberto."
      redirect_to user_path, status: :see_other
    else
      @family_member.destroy
      redirect_to family_members_path, status: :see_other
    end
  end

  private

  def set_family_member
    @family_member = FamilyMember.find(params[:id])
  end

  def family_member_params
    params.require(:family_member).permit(:first_name, :last_name, :kinship,
                                          :description, :profile_title, :value_hour, :photo)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[show destroy]

  def index
    @orders = Order.all
    @user_orders = current_user.orders
    @initials = "#{current_user.first_name[0]}#{current_user.last_name[0]}"
  end

  def show
    @user = current_user
    @order_review = @user.orders.find(params[:id]).review
    @family_members = @order.family_member
    @initials = "#{current_user.first_name[0]}#{current_user.last_name[0]}"
  end

  def new
    @family_member = FamilyMember.find(params[:family_member_id])
    @order = Order.new
    @order.family_member = @family_member
  end

  def create
    @order = Order.new(rent_date: order_params["rent_date"],
                       quantity_hour: order_params[:quantity_hour],
                       family_member_id: params[:family_member_id])
    date = Date.new(order_params["rent_date(1i)"].to_i,
                    order_params["rent_date(2i)"].to_i,
                    order_params["rent_date(3i)"].to_i)
    @order.rent_date = date
    @order.user = current_user

    if Order.where(rent_date: date, family_member_id: params[:family_member_id]).empty? && @order.save
      redirect_to order_path(@order)
    else
      flash[:alert] = "Este membro da família já está alugado para esta data. Por favor, escolha outra data."
      render :new
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_path
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:quantity_hour, :family_member_id, :user_id, :rent_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @family_members = FamilyMember.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_order, only: %i[new create]
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def create
    @family_member = @order.family_member
    @review = Review.new(review_params)
    @review.user = current_user
    @review.order_id = @order.id
    if @review.save
      redirect_to family_member_path(@family_member), notice: 'Review criado!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_order
    @order = Order.find(params[:order_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @orders = current_user.orders
    @name = "#{current_user.first_name} #{current_user.last_name}"
    @family_member = FamilyMember.new
    @family_members = FamilyMember.where(user: current_user)
    @member_name = @family_members.map { |member| "#{member.first_name} #{member.last_name}" }
    @initials = "#{current_user.first_name[0]}#{current_user.last_name[0]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/family_members/_form.html.erb
<%= simple_form_for (@family_member) do |f| %>
  <div class="form-inputs scroll-form">
    <%= f.error_notification %>
    <% f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors
    [:base].present? %>

    <%= f.input :first_name, :label => 'Primeiro nome'%>
    <%= f.input :last_name, :label => 'Sobrenome' %>
    <%= f.input :kinship, :label => 'Parentesco' %>
    <%= f.input :description, :label => 'Descrição',
                              :placeholder => 'Uma breve descrição de seu familiar'%>
    <%= f.input :profile_title, :label => 'Título' %>
    <%= f.input :value_hour, :label => 'Valor por hora' %>
    <%= f.input :photo, as: :file, :label => 'Foto' %>
  </div>

  <div class="form-actions pt-4">
    <%= f.submit "Cadastrar", class: "btn btn-outline-warning shadow-sm"%>
  </div>
<% end %>

app/views/family_members/edit.html.erb
<div class="container mt-5">
  <h1>Edite seu familiar! <%= @family_member.first_name %></
  <% render 'form'%>
  <%= link_to 'Show', @family_members, class: "btn btn-success" %> |
  <%= link_to 'Back', @family_members_path, class: "btn btn-success" %>
</div>

app/views/family_members/index.html.erb
<%= render 'shared/banner'%>

<div class="container mt-5">
  <div class="row mt-2">
    <div class="col-sm-3">
      <div class="card">
        <div class="card-body bg-info rounded-4 sm-3">
          <h5 class="card-title-text-family"><strong>Conforto Familiar Sob Medida</strong></h5>
          <p class="card-text">Seja para uma festa de aniversário, um jantar importante ou um simples passeio no parque, você pode encontrar o familiar ideal para cada ocasião.
          Escolha entre uma variedade de perfis cuidadosamente selecionados para atender às suas necessidades.</p>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="card">
        <div class="card-body bg-info rounded-4 sm-3">
          <h5 class="card-title-text-family"><strong>Segurança e Confiabilidade</strong></h5>
          <p class="card-text">Nossa plataforma garante uma experiência segura e confiável. Todos os familiares passam por um rigoroso processo de seleção e verificação de antecedentes para garantir que você esteja em boas mãos.</p>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
    <div class="card">
      <div class="card-body bg-info rounded-4 sm-3">
        <h5 class="card-title-text-family"><strong>Facilidade de Uso</strong></h5>
        <p class="card-text">Alugar um familiar nunca foi tão fácil! Basta navegar em nossa plataforma intuitiva, escolher o perfil que melhor se adapta às suas necessidades e fazer a reserva. É simples assim!</p>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body bg-info rounded-4 sm-3">
        <h5 class="card-title-text-family"><strong> Variedade de Serviços </strong></h5>
        <p class="card-text">Além de oferecer companhia para eventos sociais, nossos familiares estão disponíveis para uma variedade de serviços, desde tutoria acadêmica até assistência em tarefas domésticas. Não importa qual seja a sua necessidade!</p>
      </div>
    </div>
  </div>
</div>
  <div class="container mt-5">
    <h1 class="text-center">Nossos Familiares</h1>
    <p class="text-center">Conheça alguns dos familiares disponíveis para aluguel</p>
    <div class="d-flex flex-wrap my-2 justify-content-around mt-5 mb-5">
    <% if !@family_members.empty? %>
      <% @family_members&.first(6).each do |family_member| %>
        <div class="card bg-white rounded-4 shadow w-25 m-3">
          <div class="d-flex justify-content-center pt-2 mt-2">
            <%= cl_image_tag(family_member.photo.key, :transformation=>[  {:aspect_ratio=>"1.2",:height=>230, :crop=>"fill"} ]) %>
          </div>
          <div class="card-body">
            <h5><%= family_member.first_name %> <span class="wefont-ight-normal"><%= family_member.last_name %></span></h5>
            <p><%= family_member.description %></p>
            <div class="d-flex align-items-end justify-content-between pt-3">
              <div>
                <% if family_member.reviews.sample %>
                  <i class="fa-solid fa-star" style="color: #FFD43B"></i><small class="flex-grow-2"> <%= family_member.reviews.sample.rating%>/5</small>
                <% else %>
                  <i class="fa-solid fa-star" style="color: #FFD43B"></i><small class="flex-grow-2"> -/5</small>
                <% end %>
              </div>
              <%= link_to "Saiba mais!", family_member_path(family_member.id), class: "btn btn-warning rounded-3 shadow-sm" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
</div>

app/views/family_members/new.html.erb
<div class="container mt-5 text-allign">
  <h1>Cadastrar seu familiar</h1>
</div>

<div class="container my-5 flex-item-align-text">
  <%= render 'form' %>
  <%= link_to 'Voltar', family_members_path, class: "btn btn-success" %>
</div>

app/views/family_members/show.html.erb
<div class="container">
  <div class="d-flex align-items-center justify-content-around mt-5 mb-3">
    <%= link_to "/", class: "m-0" do %>
      <div class="rounded-3 p-2 shadow-sm" style="background-color: #FCF5EA ">
        <i class="fa-solid fa-arrow-left fa-2xl" style="color: #F3DFBD"></i>
      </div>
    <% end %>
    <strong><h1><%= @family_member.profile_title.upcase %></h1></strong>
    <%= link_to new_family_member_order_path(@family_member), class: "m-0" do %>
      <div class="rounded-3 p-2 shadow-sm" style="background-color: #FCF5EA">
        <i class="fa-solid fa-people-pulling fa-2xl shadow" style="color: #F3DFBD;"></i>
      </div>
    <% end %>
  </div>
  <div class="d-flex flex-column justify-content-center align-items-center">
    <div class="d-flex justify-content-center align-items-center w-100">
      <%= cl_image_tag(@family_member.photo.key, class:'mt-3 w-50 shadow-sm border rounded-4') %>
    </div>
    <div class="d-flex flex-column justify-content-center align-items-center mb-3 mt-2 w-100">
      <% total_rating = 0 %>
      <% @reviews.each do |review| %>
        <% total_rating += review.rating %>
      <% end %>
      <% average_rating = @reviews.any? ? (total_rating.to_f / @reviews.size).round(2) : 0 %>
      <div class="d-flex flex-column justify-content-around w-50">
        <h2><strong><%= @name %></strong></h2>
        <span class="d-flex">
          <p class="me-2"><%= average_rating %>/5</p>
          <% if @reviews.size == 0 %>
            <p class="text-secondary text-opacity-50"><%= @reviews.size %> avaliações</p>
            <% elsif @reviews.size == 1 %>
            <p class="opacity-50"><%= @reviews.size %> avaliação</p>
            <% else %>
            <p class="opacity-50"><%= @reviews.size %> avaliações</p>
          <% end %>

        </span>
        <p><%= "R$#{@family_member.value_hour}" %>0/hr</p>
      </div>
      <div class="d-flex flex-column justify-content-start w-50">
        <h5>Por que me alugar?</h5>
        <p> <%= @family_member.description %></p>
      </div>
    </div>
  </div>
  <div class="d-flex flex-column align-items-center justify-content-center mb-3 w-100" data-controller="untoggle">
    <span class="d-flex justify-content-between w-50 mb-3 border-top pt-2">
      <h5>Avaliações (<%= @reviews.size %>)</h5>
      <p data-action="click->untoggle#show" class="text-secondary f-review-90 btn p-0 m-0 border border-0">Mostrar todas</p>
    </span>
    <div class="d-flex justify-content-center d-none w-100"  data-untoggle-target="togglableElement">
      <% @reviews.each do |review| %>

        <div class="justify-content-center mt-2">
          <div class="card m-0 justify-content-start align-items-start mb-3">
            <div class="card-body w-100">
              <p class="card-text"><%= review.content %></p>
              <div class="d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center">
                  <% if user_signed_in? %>
                    <% if current_user.photo.key %>
                      <%= cl_image_tag(current_user.photo.key, height: 45, width: 45, crop: :thumb, class: "avatar-small", alt: "dropdown menu", gravity: :face) %>
                    <% else %>
                      <span class="d-flex justify-content-center align-items-center text-warning fs-5 avatar-small" style="background-color:#F4E0BE">
                        <%= current_user.first_name[0].capitalize %>
                      </span>
                    <% end %>
                  <% end %>
                  <p class="card-text m-0 ms-2"><%= review.user.first_name %></p>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                  <p class="m-0 me-2">Avaliação: <%= review.rating %>/5</p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        </div>

      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alugue Meu Familiar - Conectando Lares e Corações</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,200;0,300;0,400;0,800;1,100;1,700;1,800&family=Protest+Guerrilla&family=Protest+Riot&family=Protest+Strike&family=Roboto+Slab:wght@300;400;600;800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="body-content ">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container">
  <div class="my-card">
    <h1 class="text-center mt-2"> <strong>Seus pedidos<strong> </h1>
    <div class="d-flex flex-column align-items-center">
      <% @user_orders.each do |order| %>
      <div class="d-flex flex-column justify-content-center align-items-center p-2 border border-warning rounded-4 mb-2 w-75 shadow-sm">
        <p class="m-0 p-0 pb-2 pt-1"><strong>Pedido número:</strong> ID#RMF<%= @initials %><%= order.id %></p>
        <p class="m-0 p-0 pb-2">Criada em: <%= order.created_at.strftime("%d/%m/%Y") %> </p>
        <p>Aluguel agendado para: <%= order.rent_date.strftime("%d/%m/%Y") %></p>
        <%= link_to "Detalhes do pedido", order_path(order), class: "btn btn-warning rounded-3" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<div class="container">
  <div class="d-flex flex-column justify-content-center align-items-center">
    <div class="w-75 mt-5 pt-4 text-allign">
      <h1>Novo Pedido</h1>
      <p>Alugue uma família temporária</p>
    </div>

    <div class="w-75 mt-4 mb-5 pb-5 flex-item-align-text">
      <%= simple_form_for [@family_member, @order] do |f| %>
      <%= f.error_notification %>
      <% f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors
      [:base].present? %>
      <div class="form-inputs">
        <%= f.input :quantity_hour,:label => "Quantidade de horas" %>
        <%= f.input :rent_date, as: :date, :label => "Data de aluguel" %>
      </div>
      <div class="form-actions d-flex justify-content-between mt-4 pt-2">
        <%= f.submit 'Criar', class: "btn btn-outline-warning w-25 fw-bold"%>
        <%= link_to 'Voltar', orders_path, class: "btn btn btn-outline-warning w-25 fw-bold" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="my-card">
    <div class="d-flex flex-column align-items-center p-2">
      <h1 class="mt-1 mb-3">Detalhes do pedido</h1>
      <span>
        <p class="m-0 p-0 pb-2 pt-1"><strong>Pedido número:</strong> ID#RMF<%= @initials %><%= @order.id %></p>
        <p class="m-0 p-0 pb-2 pt-1"><strong>Nome: </strong><%= @order.family_member.first_name %> <%= @order.family_member.last_name %></p>
        <p class="m-0 p-0 pb-2 pt-1"><strong>Quantidade de horas alugadas: </strong><%= @order.quantity_hour %></p>
        <p class="m-0 p-0 pb-2 pt-1"><strong>Criada em: </strong><%= @order.created_at.strftime("%d/%m/%Y") %></p>
        <p class="m-0 mb-1 p-0 pb-2 pt-1"><strong>Aluguel agendado para: </strong><%= @order.rent_date.strftime("%d/%m/%Y") %></p>
      </span>
    </div>
    <div class="d-flex justify-content-between mt-3 mb-2">
      <% if current_user && @order_review == nil %>
        <%= link_to "Avaliar", new_order_review_path(@order), class: "btn btn-warning" %>
      <% end %>
      <%= link_to "Cancelar", order_path(@order), data: { turbo_method: :delete }, id: "cancel-order", class: "btn btn-outline-warning" %>
      <%= link_to "Voltar", orders_path, class: "btn btn-warning" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <div class="d-flex flex-column justify-content-center align-items-center">
    <div class="w-75 mt-5 pt-4 text-allign">
      <h1>Criar review</h1>
      <p>Escreva um review para o seu pedido</p>
    </div>

    <div class="w-75 mt-4 mb-5 pb-5 flex-item-align-text">
      <%= simple_form_for [@order, @review] do |f| %>
      <%= f.error_notification %>
      <% f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors
      [:base].present? %>
      <div class="form-inputs">
        <%= f.input :content, :label => 'Escreva seu review', class: "text-warning" %>
        <%= f.input :rating, :label => 'Dê uma nota de 1 a 5'%>
      </div>
      <div class="form-actions d-flex justify-content-between mt-4 pt-2">
        <%= f.submit 'Finalizar', class: "btn btn-outline-warning w-25 fw-bold"%>
        <%= link_to 'Voltar', orders_path, class: "btn btn btn-outline-warning w-25 fw-bold" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner d-flex flex-column justify-content-center align-items-center text-center">
  <h1 class="mb-4">
    <span> Rent My Family </span>
  </h1>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="d-flex flex-grow-1 footer text-center m-0 ">
  <!-- Grid container -->
  <div class="pb-0 m-0">
    <!-- Section: Social media -->
    <section class="mb-2">
      <!-- Facebook -->
      <a
      data-mdb-ripple-init
        class="btn text-white btn-floating m-1 rounded-circle shadow-sm"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        data-mdb-ripple-init
        class="btn text-white btn-floating m-1 rounded-circle shadow-sm"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        data-mdb-ripple-init
        class="btn text-white btn-floating m-1 rounded-circle shadow-sm"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        data-mdb-ripple-init
        class="btn text-white btn-floating m-1 rounded-circle shadow-sm"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        data-mdb-ripple-init
        class="btn text-white btn-floating m-1 rounded-circle shadow-sm"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        data-mdb-ripple-init
        class="btn text-white btn-floating m-1 rounded-circle shadow-sm"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center d-flex">
    <p class="m-0 me-2">© 2024 Copyright:</p>
    <a class="text-warning" href="https://rentmyfamily.com/">rentmyfamily.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon shadow-sm bg-info"
  <div class="container-fluid">
    <%= link_to "/", class: "m-0 ms-3" do %>
      <%= image_tag('logo_rent_my_family', class: "vh-10 logo-nav") %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item active me-2">
            <p class="navbar-text m-0 text-warning" >Olá, <%= current_user.first_name %> </p>
          </li>
          <li class="nav-item dropdown position-static d-flex align-items-center ms-1">
          <a href="#" class="me-2 text-decoration-none" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user.photo.key %>
            <%= cl_image_tag(current_user.photo.key, height: 45, width: 45, crop: :thumb, class: "avatar-small", alt: "dropdown menu", gravity: :face) %>
          <% else %>
            <span class="d-flex justify-content-center align-items-center text-warning fs-5 avatar" style="background-color:#F4E0BE">
              <%= current_user.first_name[0].capitalize %>
            </span>
          <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end bg-info" aria-labelledby="navbarDropdown">
              <%= link_to "Perfil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Pedidos", orders_path(current_user), class: "dropdown-item" %>
              <%= link_to "Sair", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Entrar", new_user_session_path, class: "nav-link text-warning" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div